### ISSUE TITLE
New Name Syntax Not Displayed in Loadouts

### ISSUE THREAD

**Issue by claytondaley** [RuneManager/RuneManager#185]
e.g. vigor

![image](https://user-images.githubusercontent.com/1097439/189535269-cb1783e3-2fa7-45e9-8896-fa24f7852533.png)

**Comment by kgoroway** [comment]
Likely an easy fix.  It is probably grabbing Name instead of FullName.
Fixing now.

**Comment by kgoroway** [comment]
![image](https://user-images.githubusercontent.com/5879503/189535511-e06157a2-82d2-4a0f-bdf7-fed693fb4df2.png)

Seems fine to me?

**Comment by claytondaley** [comment]
I'm going to close for now as "can't replicate" and reopen if I see it again (so we'll at least know to try and seek a cause).
