### ISSUE TITLE
siege team output

### ISSUE THREAD

**Issue by godshades** [RuneManager/RuneManager#27]
Hi, thanks for your work 
But can we get list of all defend team in siege mode ?

**Comment by Skibisky** [comment]
Hi, can you please clarify a little?

Do you want to be able to tag monsters that are in siege teams, or have siege monsters auto-tagged?  
Or do you want to view your guilds defense teams?  

I guess what would help me the most, is what are you planning to do with this information?

**Comment by godshades** [comment]
I just want view all team for easy control and setup defend :D

**Comment by godshades** [comment]
Hi @Skibisky , how about this feature?
Can you implement this? :D 
Currently I need check each member defend win rate and fill to excel, need too much time T.T

**Comment by claytondaley** [comment]
@godshades if you're still active, I assume you're aware of SWGT

Presumably that would close this issue.

**Comment by claytondaley** [comment]
Closed unless we hear more.
