### ISSUE TITLE
New monsters aren't included?

### ISSUE THREAD

**Issue by Karl115** [RuneManager/RuneManager#62]
Hi,
first of all thanks for your great work here. I love the tool.
Now to my problem. I got one of the relativly new beast riders (Barabara). But I can't create a build for her. I added the error message.

Thanks in advance

![grafik](https://user-images.githubusercontent.com/64576913/80680688-87cd8080-8abf-11ea-9d69-60dc0083f597.png)

**Comment by Skibisky** [comment]
Thanks for the screenshot.
Looks like Beast Riders have a new modifier for skills, I'll try and get that in soon

**Comment by claytondaley** [comment]
This should be fixed.
